server_address: ":8080"

binance_api_key: "your_binance_api_key"
binance_secret: "your_binance_secret"
binance_api_endpoint: "https://api.binance.com/api/v3"

bybit_api_key: "your_bybit_api_key"
bybit_secret: "your_bybit_secret"
bybit_api_endpoint: "https://api.bybit.com/v2/public"

okex_api_key: "your_okex_api_key"
okex_secret: "your_okex_secret"
okex_api_endpoint: "https://www.okex.com/api/spot/v3"
